# Generated by Django 4.2 on 2023-04-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
