# Generated by Django 4.2 on 2023-04-07 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_questioncomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questioncomment',
            old_name='content',
            new_name='comment_text',
        ),
    ]
