# Generated by Django 4.2 on 2023-04-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='helpful',
            field=models.BooleanField(default=False),
        ),
    ]
