# Generated by Django 4.2 on 2023-04-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_answervote'),
    ]

    operations = [
        migrations.AddField(
            model_name='stackoverflowuser',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
