# Generated by Django 4.2 on 2023-04-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_stackoverflowuser_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stackoverflowuser',
            name='about',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stackoverflowuser',
            name='link',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
