# Generated by Django 4.2 on 2023-04-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_alter_stackoverflowuser_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stackoverflowuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/default.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
