# Generated by Django 4.2 on 2023-04-10 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_stackoverflowuser_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stackoverflowuser',
            name='profile_pic',
        ),
    ]
